#!/usr/bin/env python3
"""Generate a C header with LQR LUT arrays from a CSV file.

Expected CSV header includes:
  hip,K0,K1,K2,K3[,theta_eq,u_eq]

Outputs a header that defines:
  LQR_LUT_SIZE, kHipLut, kLqrLut, kThetaEq, kUEq
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate lqr_lut_data.h from lqr_lut.csv")
    parser.add_argument("csv", type=Path, help="Path to lqr_lut.csv")
    parser.add_argument("--out", type=Path, default=None, help="Output header path (default: stdout)")
    parser.add_argument("--guard", type=str, default="CONTROL_LQR_LUT_DATA_H", help="Header guard")
    return parser.parse_args()


def format_float(x: float) -> str:
    return f"{x:.6f}f"


def main() -> None:
    args = parse_args()

    with args.csv.open(newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if not rows:
        raise SystemExit("CSV is empty")

    fields = {k.strip() for k in rows[0].keys() if k is not None}
    required = {"hip", "K0", "K1", "K2", "K3"}
    if not required.issubset(fields):
        raise SystemExit(f"CSV missing required columns: {sorted(required - fields)}")

    has_theta = "theta_eq" in fields
    has_u = "u_eq" in fields

    hip = [float(r["hip"]) for r in rows]
    k0 = [float(r["K0"]) for r in rows]
    k1 = [float(r["K1"]) for r in rows]
    k2 = [float(r["K2"]) for r in rows]
    k3 = [float(r["K3"]) for r in rows]
    theta = [float(r["theta_eq"]) for r in rows] if has_theta else [0.0] * len(rows)
    ueq = [float(r["u_eq"]) for r in rows] if has_u else [0.0] * len(rows)

    lines = []
    lines.append("// Generated by tools/lqr_lut_to_header.py")
    lines.append(f"// Source: {args.csv}")
    lines.append(f"// Generated: {dt.datetime.now().isoformat(timespec='seconds')}")
    lines.append("")
    lines.append(f"#ifndef {args.guard}")
    lines.append(f"#define {args.guard}")
    lines.append("")
    lines.append(f"#define LQR_LUT_SIZE {len(rows)}")
    lines.append("")

    lines.append("static const float kHipLut[LQR_LUT_SIZE] = {")
    for v in hip:
        lines.append(f"    {format_float(v)},")
    lines.append("};\n")

    lines.append("static const float kLqrLut[LQR_LUT_SIZE][4] = {")
    for a, b, c, d in zip(k0, k1, k2, k3):
        lines.append(f"    {{ {format_float(a)}, {format_float(b)}, {format_float(c)}, {format_float(d)} }},")
    lines.append("};\n")

    lines.append("static const float kThetaEq[LQR_LUT_SIZE] = {")
    for v in theta:
        lines.append(f"    {format_float(v)},")
    lines.append("};\n")

    lines.append("static const float kUEq[LQR_LUT_SIZE] = {")
    for v in ueq:
        lines.append(f"    {format_float(v)},")
    lines.append("};\n")

    lines.append(f"#endif /* {args.guard} */\n")

    content = "\n".join(lines)
    if args.out:
        args.out.write_text(content)
    else:
        print(content)


if __name__ == "__main__":
    main()
